version: '3.8'

services:
  fingerprint-api:
    build: .
    container_name: fingerprint-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./plots:/app/plots
    restart: unless-stopped
